version: "2"
services:
  server:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - "3000:3000"
    networks:
      - meanstack-net
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - meanstack-net
networks:
  meanstack-net:
    driver: bridge
